### ISSUE TITLE
Sending a msg with a link doesn't work

### ISSUE THREAD

**Issue by Alex-Poon** [scrubjay55/Reddit_ChatBot_Python#5]
```
@chatbot.event.on_ready
def test(_):
    dm_channel = cb.create_direct_channel('user')
    cb.send_message("test apple.com", dm_channel.channel_url)
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 69, in run
    reraise(*_capture_exception())
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/sentry_sdk/integrations/threading.py", line 67, in run
    return old_run_func(self, *a, **kw)
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/Reddit_ChatBot_Python/ws_client.py", line 116, in _response_loop
    if func(resp):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/Reddit_ChatBot_Python/_events.py", line 37, in hook
    return func(resp)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/Reddit_ChatBot_Python/_events.py", line 26, in hook
    return func(resp)
  File "main.py", line 167, in run
    job(chatbot)
  File "main.py", line 157, in job
    inviteMsg(author_name, item.subreddit, chatbot)
  File "main.py", line 124, in inviteMsg
    dm_channel = cb.create_direct_channel(name)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/Reddit_ChatBot_Python/chatbot.py", line 209, in create_direct_channel
    channel = self.__tools.create_channel(nicknames=[nickname], group_name="",
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/Reddit_ChatBot_Python/_api/tools.py", line 139, in create_channel
    response = self._handled_req(method='POST', uri=f'{S_REDDIT}/api/v1/sendbird/group_channels',
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/Reddit_ChatBot_Python/_api/tools.py", line 41, in _handled_req
    raise Exception(response.json())
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

**Comment by Alex-Poon** [comment]
I'm seeing an odd GET request outside the webstocket

```
curl 'https://sendbirdproxyk8s.chat.redditmedia.com/v3/group_channels/sendbird_group_channel_**<redacted>**/members?token=&limit=20&order=member_nickname_alphabetical&muted_member_filter=all&member_state_filter=all&show_member_is_muted=true&show_read_receipt=true&show_delivery_receipt=true&nickname_startswith=**apple.com**' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'Session-Key: **<redacted>**' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'SB-User-Agent: JS%2Fc3.0.148%2F%2F' \
  -H 'SendBird: JS,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML. like Gecko) Chrome/91.0.4472.114 Safari/537.36,3.0.148,2515BDA8-9D3A-47CF-9325-330BC37ADA13' \
  -H 'Request-Sent-Timestamp: 1626734382734' \
  -H 'Origin: https://www.reddit.com' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://www.reddit.com/' \
  -H 'Accept-Language: en-US,en;q=0.9,lb;q=0.8' \
  --compressed
```

**Comment by scrubjay55** [comment]
I probably know why this happens. Just letting you know that it will be fixed as soon as I get the chance.

**Comment by scrubjay55** [comment]
Can you pull and see the exception message again with the latest changes I pushed? @Alex-Poon
