### ISSUE TITLE
accept_chat_invite error: in_data missing 'created_by'

### ISSUE THREAD

**Issue by LeeCook1** [scrubjay55/Reddit_ChatBot_Python#7]
I want to first begin by saying I am highly impressed with this module and the perceived time and energy it took for you to reverse eng the chat process. 

To begin, there was an issue with accepting chat invites. The problem starts when `created_by` is `None` within the dictionary returned by `response.json()` [here](https://github.com/scrubjay55/Reddit_ChatBot_Python/blob/3a899dd9ea2b911f400b5f19ad05cceef2f3c23a/Reddit_ChatBot_Python/_api/tools.py#L116). 

Continuing on, when passed down to the `Channel.__init__`, at line [39](https://github.com/scrubjay55/Reddit_ChatBot_Python/blob/3a899dd9ea2b911f400b5f19ad05cceef2f3c23a/Reddit_ChatBot_Python/_api/models.py#L39) `in_data.get('created_by')` will return `None` and that will be passed to `User.__init__`. `User.__init__` expects a dictionary, thus errors as mentioned below. 

I do not know why created_by is empty, as I do not understand the intricacies of the REST API that is being utilised and its correlation with the Reddit data. Thus, I am stuck here. 

### Setup:
macOS Catalina v10.15.7
python 3.8.2

### Traceback:
```
Exception ignored in thread started by: <bound method WebSockClient._response_loop of <Reddit_ChatBot_Python.ws_client.WebSockClient object at 0x10b10d760>>
Traceback (most recent call last):
  File "/Users/leoc/Workspace/Reddit_Chat/.venv/lib/python3.8/site-packages/Reddit_ChatBot_Python/ws_client.py", line 102, in _response_loop
    if func(resp):
  File "/Users/leoc/Workspace/Reddit_Chat/.venv/lib/python3.8/site-packages/Reddit_ChatBot_Python/_events.py", line 15, in hook
    return func(resp)
  File "/Users/leoc/Workspace/Reddit_Chat/.venv/lib/python3.8/site-packages/Reddit_ChatBot_Python/_events.py", line 97, in hook
    return func(resp)
  File "chat_pract.py", line 38, in on_invite
    chatbot.accept_chat_invite(resp.channel_url)
  File "/Users/leoc/Workspace/Reddit_Chat/.venv/lib/python3.8/site-packages/Reddit_ChatBot_Python/chatbot.py", line 198, in accept_chat_invite
    group = super().accept_chat_invite(channel_url)
  File "/Users/leoc/Workspace/Reddit_Chat/.venv/lib/python3.8/site-packages/Reddit_ChatBot_Python/_api/tools.py", line 116, in accept_chat_invite
    return Channel(response.json())
  File "/Users/leoc/Workspace/Reddit_Chat/.venv/lib/python3.8/site-packages/Reddit_ChatBot_Python/_api/models.py", line 39, in __init__
    self.created_by: User = User(in_data.get('created_by'))
  File "/Users/leoc/Workspace/Reddit_Chat/.venv/lib/python3.8/site-packages/Reddit_ChatBot_Python/_api/models.py", line 89, in __init__
    self.is_blocking_me: Optional[bool] = in_data.get('is_blocking_me')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by scrubjay55** [comment]
thanks for letting me know. fixed in 3a899dd turns out created_by field is `null` in invitations.

**Comment by LeeCook1** [comment]
I am curious, how were you able to confirm that?

I put this line in to compensate: 
<img width="597" alt="Screenshot 2022-01-04 at 8 56 48 AM" src="https://user-images.githubusercontent.com/32077834/148078504-5553e4aa-416c-4a68-a577-54d16ccf6c53.png">

Also, if I had a question that wasn't 'issue' worthy, is there another means I can reach out to you?

**Comment by scrubjay55** [comment]
I use mitm proxy to inspect websocket and http requests of the official app.

And yeah you could do that too but it would be basically checking for all those fields of the `User` inside an empty dict.
You can write from reddit dms. I use it for this kind of stuff: u/perokisdead
